name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for the issue. Contributors or those that have write acces are making the fix"
        pr-message: "Thank you for the PR. It has a chance of getting just closed or merged"
